### ISSUE TITLE
find_julia not finding juliaup default channel

### ISSUE THREAD

**Issue by pbelliveau-ideon** [jlapeyre/find_julia#5]
## Summary

Hi there. I'm really liking the approach of julia_project and find_julia. I was trying this out on a linux machine that is using juliaup but only has a single version of julia installed. find_julia was failing to find the julia executable in this case---i.e. `find_julia.find()` returns `None`. After debugging this I found that on this machine the `config` dict returned by `find_julia.juliaup._get_juliaup_config()` contained a valid julia version in `config["DefaultChannel"]` but that `config["OtherChannels"]` was empty.

## Additional Info

- Platform: Linux
- python version 3.10.12
- julia version 1.10.1
- juliaup version: 1.12.5
- Steps to reproduce:
  1. Download juliaup via `curl -fsSL https://install.julialang.org | sh`
  2. Follow default installation instructions
  3. `pip install find_julia`
  4. In python run
  ```
  from find_julia import find
  a = find()
  ```

## Possible fix

I was able to fix this for my use case by changing `find_julia.juliaup.version_path_list` to the following:
```
def version_path_list():
    """
    Return a list of julia versions and executable paths as two-tuples.

    Each two-tuple is of the form `(version, path)`.
    """
    config = _get_juliaup_config()
    if config is None:
        return []

    chlist = []
    if "DefaultChannel" in config:
        chlist.append((config["DefaultChannel"]["Version"], config["DefaultChannel"]["File"]))
    other_channels = config["OtherChannels"]
    for chan in other_channels:
        chlist.append((chan['Version'], chan['File']))
    return chlist
```

I'm happy to make a PR with this fix but thought I'd start with just an issue as I don't know enough about juliaup or find_julia to know if the proposed fix is really a good or robust approach.

**Comment by jlapeyre** [comment]
Hello. Thanks for the bug report. Your fix looks fine. I find the following slightly cleaner:
```python
    channels = config["OtherChannels"]
    channels.append(config["DefaultChannel"])
    chlist = []
    for chan in channels:
        chlist.append((chan['Version'], chan['File']))
```
Now that I look at it again, I think this is better:
```python
    channels = config["OtherChannels"]
    channels.append(config["DefaultChannel"])
    return [(chan['Version'], chan['File']) for chan in channels]
```

**Comment by pbelliveau-ideon** [comment]
Thanks for fixing this!
